---
galaxy_info:
  author: Jorge Medina
  description: Setup common operating system tasks.
  company: KronOps
  license: MIT
  min_ansible_version: 2.8
  platforms:
  - name: macos
    versions:
    - catalina
  categories:
  - destkop
dependencies: []

